version: '3'

services:
  my-measures-db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - 8081:8080

volumes:
  db-data: {}
