export const BALANCE_SHEET_ADD = 'BALANCE_SHEET_ADD'
export const BALANCE_SHEET_LOAD_ASYNC = 'BALANCE_SHEET_LOAD_ASYNC'

export const ADD_TODO = 'ADD_TODO'
export const ADD_WEIGHT = 'ADD_WEIGHT'
export const LOAD_WEIGHT_ASYNC = 'LOAD_WEIGHT_ASYNC'
